### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by ktoso** [michaelpisula/akka-journal-inmemory#1] opened 2014-04-19 19:03 UTC
This in-memory journal seems to get used by some projects I've seen out there (just found this one https://github.com/pawelkaczor/ddd-leaven-akka ).
Would be great to have it in maven central :-)

PS: You're listed as community plugin on http://akka.io/community already :-)

**Comment by michaelpisula** [comment] 2014-04-22 09:25
Cześć Konrad,

cool to see that people are using it :-) I'll take a look into what it takes to publish it. Some of my colleagues already have projects they published, so I suppose this will not be a major issue.

I added the plugin to the community page myself, but I think the bigger visibility boost came from the mention you guys gave me on twitter some week ago ;-)

**Comment by ktoso** [comment] 2014-04-22 09:27
Cool / _doskonale_! :-)
Yes, getting access to maven central is pretty easy - all is explained here: https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

Please update the community site once you've published :-)

**Comment by michaelpisula** [comment] 2014-05-03 09:34
It took some time, but finally I got around to publishing it.
Hopefully everythings works as intended :-)

Will plug it into my project on monday to test, will then update the community page if everything worked fine.

**Comment by ktoso** [comment] 2014-05-03 13:03
Seems good http://search.maven.org/#search%7Cga%7C1%7Ccom.github.michaelpisula

Grats - I wish you a load of users then ;-)

**Comment by michaelpisula** [comment] 2014-05-09 17:47
Should work now, I'm closing the issue and will edit the community page.

**Closed as completed by michaelpisula** 2014-05-09 17:47 UTC
